export enum ErrorCode {
  // Common
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Upload
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',

  // Storage (S3)
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
  STORAGE_DELETE_FAILED = 'STORAGE_DELETE_FAILED',
  STORAGE_ACCESS_DENIED = 'STORAGE_ACCESS_DENIED',
}
